GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDI0NGQ3MDFmYTk2NTFjNWQxNjcyN2IiLCJpYXQiOjE2MTMwODU3ODAsImV4cCI6MTY0NDY0MzM4MH0.FkufqMgVdxPpe559okLnXxL03KTfVSdASKePtoKWyx8

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "İbrahim Yener",
    "surName": "Yılmaz",
    "userName": "ibraoffical",
    "email": "yilmaz.ibra@gmail.com",
    "password": "123456"
}

###

DELETE http://localhost:3000/api/users/60153902b8a3ab39c060fc1e
Content-Type: application/json

###

PATCH http://localhost:3000/api/users/60157fabda74a33af4d7b17c
Content-Type: application/json

{
    "balance": "10000"
}

###
PATCH http://localhost:3000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDE5OGQyODdhODkxYzNiY2M1NTU5MjQiLCJpYXQiOjE2MTIzODIzODEsImV4cCI6MTYxMjQ2ODc4MX0.0Js8vwFfLdcPry-FY7EvxtIDWtSEJeRNudRr46Teo8Q

{
    "name": "Müslüm",
    "surName": "Gürses"
}
###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "fcakal07@gmail.com",
    "password": "123456"
}